plugins { id 'com.android.application' }

android {
    namespace 'com.dramer.clinic'
    compileSdk 35
    defaultConfig {
        applicationId 'com.dramer.clinic'
        minSdk 26
        targetSdk 35
        versionCode 50001
        versionName '5.0.0-test1'
    }
    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
